name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Btrfs CI
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
      id: go

    - name: Setup environment
      shell: bash
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: src/github.com/containerd/btrfs
        fetch-depth: 25

    - name: Project checks
      uses: containerd/project-checks@v1
      with:
        working-directory: src/github.com/containerd/btrfs

    - name: Build
      working-directory: src/github.com/containerd/btrfs
      run: |
        make vet binaries

    - name: Build with an old version of kernel headers
      working-directory: src/github.com/containerd/btrfs
      run: |
        DOCKER_BUILDKIT=1 docker build -f hack/Dockerfile.compilation-test .
